{
  "message": "Valid installation of TensorFlow not found.\n\nPython environments searched for 'tensorflow' package:\n C:\\Users\\ygong\\AppData\\Local\\r-miniconda\\envs\\r-reticulate\\python.exe\n\nPython exception encountered:\n ImportError: Traceback (most recent call last):\n  File \"C:\\Users\\ygong\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 60, in <module>\n    from tensorflow.python._pywrap_tensorflow_internal import *\n  File \"D:\\Program Files (x86)\\R-4.1.2\\library\\reticulate\\python\\rpytools\\loader.py\", line 39, in _import_hook\n    module = _import(\nImportError: DLL load failed while importing _pywrap_tensorflow_internal: Insufficient system resources exist to complete the requested service.\n\n\nFailed to load the native TensorFlow runtime.\nSee https://www.tensorflow.org/install/errors for some common causes and solutions.\nIf you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.\n\nYou can install TensorFlow using the install_tensorflow() function.\n",
  "traceback": ["stop(tf_config()$error_message, call. = FALSE)", "on_error(result)", "py_resolve_module_proxy(x)", "`$.python.builtin.module`(keras, \"__version__\")", "keras$\"__version__\"", "keras_version()", "to_categorical(y, 2)", "eval(ei, envir)", "eval(ei, envir)", "withVisible(eval(ei, envir))", "tuning_run(\"keras_grid_search.R\", flags = list(nodes_layer1 = c(64, \n    128, 256), nodes_layer2 = c(64, 128, 256), nodes_layer3 = c(64, \n    128, 256), dropout_layer1 = c(0.2, 0.3, 0.4), dropout_layer2 = c(0.2, \n    0.3, 0.4), dropout_layer3 = c(0.2, 0.3, 0.4)), confirm = FALSE, \n    echo = FALSE, sample = 0.01)"]
}
